{% set name = "dicomifier" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lamyj/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 21adf8577f3a4475cf977e2132ef06edb15bfb263929a28e4f3dfd4411d45372
  patches:
    - meta_data.patch

build:
  number: 1
  skip: true  # [py<=35 or win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - boost-cpp
    - odil >=0.12
    - pybind11
    - python
  run:
    - boost-cpp
    - nibabel
    - numpy
    - odil >=0.12
    - python
    - python-dateutil

test:
  imports:
    - dicomifier
  commands:
    - bruker2dicom --help > /dev/null
    - dicom2nifti --help > /dev/null

about:
  home: https://github.com/lamyj/dicomifier
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Convert data from Bruker to DICOM and from DICOM to NIfTI

  description: |
    Dicomifier is a set of tools to convert Bruker data to DICOM files, and 
    DICOM files to NIfTI. It retains meta-data (e.g. MR parameters such as echo 
    time or subject parameters such as weight or height) throughout the 
    conversion process, storing them in JSON format, allowing easy access in 
    multiple environments. The meta-data from Bruker is aligned on the DICOM 
    dictionary for unified human and animal processing pipelines.

  doc_url: https://github.com/lamyj/dicomifier
  dev_url: https://github.com/lamyj/dicomifier

extra:
  recipe-maintainers:
    - lamyj
