{% set name = "dicomifier" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lamyj/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7a435bf36f659f1caaaa9ccc91dd7b75cff2727c788f0bc9a5406a91eb4bac7b
  patches: []

build:
  number: 0
  skip: true  # [py<=35 or win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - boost-cpp
    - odil >=0.12
    - pybind11
    - python
  run:
    - boost-cpp
    - nibabel
    - numpy
    - odil >=0.12
    - python
    - python-dateutil

test:
  imports:
    - dicomifier
  commands:
    - bruker2dicom --help > /dev/null
    - dicom2nifti --help > /dev/null

about:
  home: https://github.com/lamyj/dicomifier
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Convert data from Bruker to DICOM and from DICOM to NIfTI

  description: |
    Dicomifier is a set of tools to convert Bruker data to DICOM files, and 
    DICOM files to NIfTI. It retains meta-data (e.g. MR parameters such as echo 
    time or subject parameters such as weight or height) throughout the 
    conversion process, storing them in JSON format, allowing easy access in 
    multiple environments. The meta-data from Bruker is aligned on the DICOM 
    dictionary for unified human and animal processing pipelines.

  doc_url: https://github.com/lamyj/dicomifier
  dev_url: https://github.com/lamyj/dicomifier

extra:
  recipe-maintainers:
    - lamyj
